### ISSUE TITLE
Fails to build on windows outside of cygwin or msys/mingw64

### ISSUE THREAD

**Issue by xrheihwh** [patriciogonzalezvivo/thebookofshaders#422]
Two different errors I encountered. The first one is that I get the following terminal output:
```
Traceback (most recent call last):
  File "D:\Users\Matthew\downloads\thebookofshaders\src\parseBook.py", line 73, in <module>
    fileString = originalChapter.read()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\msys64\mingw64\lib\python3.11\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4870: character maps to <undefined>
make: *** [Makefile:17: pdf] Error 1
```
I fixed this by setting encoding='utf-8' in the open functions.

My second issue is something I cannot figure out why because it works with mingw64 shell.
```
Traceback (most recent call last):
  File "D:\Users\Matthew\downloads\thebookofshaders\src\parseBook.py", line 78, in <module>
    modifiedChapterString = re.sub(imgPattern, subPattern, fileString)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\msys64\mingw64\lib\python3.11\re\__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\msys64\mingw64\lib\python3.11\re\__init__.py", line 317, in _subx
    template = _compile_repl(template, pattern)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\msys64\mingw64\lib\python3.11\re\__init__.py", line 308, in _compile_repl
    return _parser.parse_template(repl, pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\msys64\mingw64\lib\python3.11\re\_parser.py", line 1081, in parse_template
    addgroup(int(this[1:]), len(this) - 1)
  File "D:\msys64\mingw64\lib\python3.11\re\_parser.py", line 1017, in addgroup
    raise s.error("invalid group reference %d" % index, pos)
re.error: invalid group reference 10 at position 4
make: *** [Makefile:17: pdf] Error 1
```

I don't know if windows was ever intended for being built on, but just wanted to file a bug report it fails to build on windows outside of some sort of POSIX emulation.

**Comment by kuantumania** [comment]
Good findings! Here's what's happening with both errors:

**Error 1 (UnicodeDecodeError):** Windows uses `cp1252` encoding by default instead of UTF-8. Your fix (`encoding='utf-8'` in `open()`) is correct.

**Error 2 (invalid group reference 10):** This is a Python `re` module issue on Windows. The replacement pattern likely contains something like `\10` which Python interprets as backreference group 10 (which doesn't exist), instead of group `\1` followed by the character `0`.

The fix is to use `r""` raw strings or escape the backslashes in the replacement pattern in `parseBook.py`. For example, change:

```python
modifiedChapterString = re.sub(imgPattern, subPattern, fileString)

If subPattern contains \1 followed by digits, replace it using a lambda:

modifiedChapterString = re.sub(imgPattern, lambda m: subPattern.replace('\\1', m.group(1)), fileString)
Or simply check parseBook.py around line 78 — the subPattern string likely has an ambiguous backreference like \10 that needs to be written explicitly as \g<1>0 in Python's re syntax:

subPattern = subPattern.replace(r'\10', r'\g<1>0')

mingw64 works because it uses a different regex engine underneath. This is a Python re portability issue, not a Windows-only limitation per se.
