### ISSUE TITLE
when trying to create PDF, make fails on OS X

### ISSUE THREAD

**Issue by mhorga** [patriciogonzalezvivo/thebookofshaders#60]
I am following the instructions, line by line. Everything goes fine until the very last make command which fails. Here is the last part of the console output:

`glslViewer ./15/blend.frag ./15/04.jpg ./15/05.jpg -s 0.5 -o ./15/tmp-blend.png
Loading ./15/04.jpg as the following uniform:
    uniform sampler2D u_tex0; // loaded
    uniform vec2 u_tex0Resolution;
Loading ./15/05.jpg as the following uniform:
    uniform sampler2D u_tex1; // loaded
    uniform vec2 u_tex1Resolution;
Will exit in 0.5 seconds.
Will save screenshot to ./15/tmp-blend.png on exit.
Traceback (most recent call last):
  File "src/parseBook.py", line 59, in <module>
    modifiedChapterString = injectShaderBlocks(folder, modifiedChapterString)
  File "src/parseBook.py", line 34, in injectShaderBlocks
    shaderString = open(shaderPath, 'r').read()
IOError: [Errno 2] No such file or directory: './appendix/    grid-making.frag'
make: *** [all] Error 1`

**Comment by julien** [comment]
Hi, 

Exact same issue here, and it seems like a missing shader.

As a quick fix, I deleted the references to this file, which are in chapter 09 and in the appendix (in the README files), but after that change, when trying to build the book it still fails with the following error:

```
! Dimension too large.
<to be read again> 
                   b
l.4830 \includegraphics{./12/accretion.jpg}

pandoc: Error producing PDF
Error in building of ./book.pdf
```
So it seems that the image file ```/12/accretion.jpg``` is too big (800 x 800 px), I resized it to half it's original size (just to test), and that fixed it.

If anyone is planning to make regular releases of the book in .pdf format I'd be interested.
We could for example use GitHub's web hooks to send the job to a server which could build the book for example :)

**Comment by patriciogonzalezvivo** [comment]
Seams that is failing on the chapters that are not finished... temporally delete all folder with numbers equals or over `12/`

**Comment by julien** [comment]
Great, thanks @patriciogonzalezvivo !

**Comment by MartinRGB** [comment]
#13
